name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Cache cargo packages and the registry index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: cargo build --verbose

      - name: Run clippy lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run rustfmt check
        run: cargo fmt --check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Cache cargo packages and the registry index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      - name: Run nextest
        run: cargo nextest run
